<div class="box">
    <div class="box-header">
        <h3 class="box-title">Danh sách tài khoản</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap"><div class="row"><div class="col-sm-6"></div><div class="col-sm-6"></div></div><div class="row"><div class="col-sm-12"><table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
            <thead>
            <tr role="row">
                <th>STT</th>
                <th>ID</th>
                <th>User Name</th>
                <th>Họ Tên</th>
                <th>Địa chỉ</th>
                <th>SĐT</th>
                <th>Email</th>
                <th>Giới tính</th>
                <th>Điểm Tích Lũy</th>
                <th>Nhóm tài khoản</th>
            </tr>
            </thead>
            <tbody>
            <?php
            $stt = 0;
            foreach($this->view['list'] as $data){
                $stt +=1;
            ?>
            <tr role="row" class="odd">
                <td><?php echo $stt; ?></td>
                <td><?php echo $data['id'] ?></td>
                <td><?php echo $data['ten_dang_nhap'] ?></td>
                <td><?php echo $data['ho_dem'].' '.$data['ten']; ?></td>
                <td><?php echo $data['dia_chi'] ?></td>
                <td><?php echo $data['so_dien_thoai'] ?></td>
                <td><?php echo $data['email'] ?></td>
                <td><?php
                    if($data['gioi_tinh']==1){
                        echo 'Nam';
                    }
                    else
                        echo 'Nữ';
                    ?></td>
                <td><?php echo $data['diem_tich_luy'] ?></td>
                <td><?php echo $data['ten_nhom'] ?></td>
            </tr>
            <?php } ?>
            </tbody>
        </table></div></div>
            <div class="row">
                <div class="col-sm-5">
                    <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Tổng số: <?php echo count($this->view['list'])?> bản ghi</div>
                </div>
                <div class="col-sm-7">
                    <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                        <?php
                        if ($this->view['total_pages'] > 1) {
                        $previous = isset($_GET['page']) ? $_GET['page'] - 1 : 1;
                        $next     = isset($_GET['page']) ? $_GET['page'] + 1 : 2;
                        if (@$_GET['page'] == 1 || !isset($_GET['page'])) {
                            $disabled1 = 'disabled';
                        } else {
                            $disabled1 = '';
                        }
                        if (@$_GET['page'] == $this->view['total_pages']) {
                            $disabled2 = 'disabled';
                        } else {
                            $disabled2 = '';
                        }
                        ?>
                        <ul class="pagination">
                            <li class="paginate_button previous <?php echo $disabled1; ?>" id="example2_previous">
                                <a class="page-link"
                                   href="?controller=admin-user&action=list&page=<?php echo $previous; ?>">Trước</a>
                            </li>
                            <?php
                            for ($page = 1; $page <= $this->view['total_pages']; $page++) {
                                if (@$_GET['page'] == $page) {
                                    $active = 'active';
                                } else {
                                    $active = '';
                                }
                                echo '<li class="paginate_button ' . $active . '"><a class="page-link" href="?controller=admin-user&action=list&page=' . $page . '">' . $page . '</a></li>';
                            }
                            ?>
                            <li class="paginate_button <?php echo $disabled2; ?>" id="example2_next">
                                <a class="page-link"
                                   href="?controller=admin-user&action=list&page=<?php echo $next; ?>">Sau</a>
                            </li>
                        </ul>
                            <?php
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.box-body -->
</div>