<!DOCTYPE html>
<html lang="vi" >
<head>
    <meta charset="UTF-8">
    <title>Đăng nhập</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">

    <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900|RobotoDraft:400,100,300,500,700,900'>
    <link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>
    <link rel="stylesheet" href="<?php echo template_url; ?>css/login.css">

</head>

<body>
<div class="pen-title">
    <h1>Đăng Nhập</h1>
</div>
<!-- Form Module-->
<div class="module form-module">
    <div class="form">
        <h2>Đăng nhập để tiếp tục sử dụng dịch vụ</h2>
        <form>
            <input type="text" placeholder="Tên đăng nhập..."/>
            <input type="password" placeholder="Mật khẩu..."/>
            <button>Đăng nhập</button>
        </form>
    </div>
    <div class="cta"><a href="#">Quên mật khẩu?</a></div>
</div>
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script  src="<?php echo template_url; ?>js/login.js"></script>

</body>

</html>
