<h2>Nội dung trong file view     </h2>
phần này dành cho từng file view
<div class="box-header with-border">
    <h3 class="box-title">Monthly Recap Report</h3>

    <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
        </button>
        <div class="btn-group">
            <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-wrench"></i></button>
            <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
            </ul>
        </div>
        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
    </div>
</div>
<!-- .box-header -->
<div class="box-body">
    <div class="row">
        <div class="col-sm-12">
            <h1>test</h1>
        <h1>Code</h1>
        <!--------------------------
      | Your Page Content Here |
      -------------------------->
<!-- /.col -->
</div>
</div>
<!-- /.row -->
</div>
<!-- ./box-body -->
<div class="box-footer">
    <div class="row">
        <div class="col-sm-12">
            <h1>test</h1>
        </div>
    </div>
    <!-- /.row -->
</div>
<?php
    echo  $this->view['msg'];
?>