<div class="box">
    <div class="box-header">
        <h3 class="box-title">Thêm mới danh mục</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <?php
        if (!empty($this->view['msg'])) {
            echo '<pre>';
            echo $this->view['msg'];
            echo '</pre>';
        }
        ?>
        <form action="" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label for="text">Tên danh mục</label>
                <input class="form-control" type="text" name="txt_ten_danh_muc">
                <label for="text">Mô tả</label>
                <textarea rows="10" class="form-control" id="content2" name="txt_mo_ta"></textarea>
                <label for="text">Hình Ảnh</label>
                <input class="form-control" type="file" name="txt_hinh_anh[]" accept=".png,.jpg,.jpeg,.gif"
                       multiple="multiple">
            </div>
            <input type="submit" value="Thêm mới" class="btn btn-info" name="btnSave">
        </form>

    </div>
    <!-- /.box-body -->
</div>
