<div class="box">
    <div class="box-header">
        <h3 class="box-title">Thêm mới bài viết</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <?php
        if (!empty($this->view['msg'])) {
            echo '<pre>';
            echo $this->view['msg'];
            echo '</pre>';
        }
        ?>
        <form action="" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label for="text">Tiêu đề</label>
                <input class="form-control" type="text" name="txt_tieu_de">
                <label for="text">Nội dung</label>
                <textarea rows="10" class="form-control" id="content2" name="txt_noi_dung"></textarea>
                <label for="text">Danh mục</label>
                <select class="form-control" name="txt_danh_muc" id="">
                    <option value="0">--Danh mục--</option>
                    <?php foreach ($this->view['list-category'] as $value) { ?>
                        <option value="<?php echo $value['id']; ?>">
                            <?php echo $value['ten_danh_muc']; ?></option>
                    <?php } ?>
                </select>
                <label for="text">Hình Ảnh</label>
                <input class="form-control" type="file" name="txt_hinh_anh[]" accept=".png,.jpg,.jpeg,.gif"
                       multiple="multiple">
            </div>
            <input type="submit" value="Thêm mới" class="btn btn-info" name="btnSave">
        </form>

    </div>
    <!-- /.box-body -->
</div>
<script src="<?php echo template_url; ?>ckeditor/ckeditor/ckeditor.js"></script>
<script>
    //    CKEDITOR.replace( 'noi_dung_ks' );
    //    CKEDITOR.replace( 'thong_tin' );
    CKEDITOR.replace("content2", {
        toolbar: [
            {name: 'basicstyles', items: ['Bold', 'Italic', 'Underline', 'Strike', '-', 'RemoveFormat']},
            {name: 'clipboard', items: ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {
                name: 'insert',
                items: ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']
            },
            {name: 'paragraph', items: ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote']},
            {name: 'links', items: ['Link', 'Unlink', 'Anchor']},
        ],
        extraPlugins: "tableresize"
    });
</script>