<div class="box">
    <div class="box-header">
        <h3 class="box-title">Sửa bài viết: <?php echo @$this->view['data']['tieu_de'] ?></h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <?php
        if (!empty($this->view['msg'])) {
            echo '<pre>';
            foreach ($this->view['msg'] as $msg){
                echo $msg.'<br>';
            }
            echo '</pre>';
        }
        if(!empty($this->view['data'])){
        $data = $this->view['data'];
        ?>
        <form action="" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label for="text">Tiêu đề</label>
                <input class="form-control" type="text" name="txt_tieu_de" value="<?php echo $data['tieu_de'] ?>">
                <label for="text">Nội dung</label>
                <textarea rows="10" class="form-control" id="content2" name="txt_noi_dung"><?php echo $data['noi_dung'] ?></textarea>
                <label for="text">Danh mục</label>
                <select class="form-control" name="txt_danh_muc" id="">
                    <option value="<?php echo $data['id_danh_muc'] ?>"><?php echo $data['ten_danh_muc'] ?></option>
                    <?php foreach ($data['list-category'] as $value) { ?>
                        <option value="<?php echo $value['id']; ?>">
                            <?php echo $value['ten_danh_muc']; ?></option>
                    <?php } ?>
                </select>
                <label for="text">Hình Ảnh Hiển Thị</label><br>
                <?php $hinh_anh = unserialize($data['hinh_anh']);?>
                <img style="width:200px;" src="<?php echo template_url.'images/img-article/'.$hinh_anh[0]; ?>"/>
                <br>
                <input class="form-control" type="file" name="txt_hinh_anh[]" accept=".png,.jpg,.jpeg,.gif"
                       multiple="multiple">
            </div>
            <input type="submit" value="Cập nhật" class="btn btn-info" name="btnSave">
        </form>
<?php } ?>
    </div>
    <!-- /.box-body -->
</div>