<div class="box">
    <div class="box-header">
        <h3 class="box-title">Danh sách bài viết</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap"><div class="row"><div class="col-sm-6"></div><div class="col-sm-6"></div></div><div class="row"><div class="col-sm-12"><table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                        <thead>
                        <tr role="row">
                            <th>STT</th>
                            <th>ID</th>
                            <th>Cập nhật lần cuối</th>
                            <th>Ngày đăng</th>
                            <th>Người đăng</th>
                            <th>Tiêu đề</th>
                            <th>Nội dung</th>
                            <th>Hình ảnh</th>
                            <th>Danh mục</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        $stt = 0;
                        foreach($this->view['list'] as $data){
                            $stt +=1;
                            ?>
                            <tr role="row" class="odd">
                                <td><?php echo $stt; ?></td>
                                <td><?php echo $data['id'] ?></td>
                                <td><?php if(empty($data['ngay_cap_nhat'])){ echo $data['ngay_dang'];} else echo $data['ngay_cap_nhat']; ?></td>
                                <td><?php echo $data['ngay_dang'] ?></td>
                                <td><?php echo $data['ten_dang_nhap'] ?></td>
                                <td><?php echo $data['tieu_de'] ?></td>
                                <td><?php echo $data['noi_dung']; ?></td>
                                <td><img style="max-width:100px;" src="<?php $hinh_anh = unserialize($data['hinh_anh']);foreach($hinh_anh as $value){ echo  template_url.'images/img-article/'.$value; }?>" alt=""></td>
                                <td><?php echo $data['ten_danh_muc'] ?></td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table></div></div>
            <div class="row">
                <div class="col-sm-5">
                    <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Tổng số: <?php echo count($this->view['list'])?> bản ghi</div>
                </div>
                <div class="col-sm-7">
                    <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                        <?php
                        if ($this->view['total_pages'] > 1) {
                            $previous = isset($_GET['page']) ? $_GET['page'] - 1 : 1;
                            $next     = isset($_GET['page']) ? $_GET['page'] + 1 : 2;
                            if (@$_GET['page'] == 1 || !isset($_GET['page'])) {
                                $disabled1 = 'disabled';
                            } else {
                                $disabled1 = '';
                            }
                            if (@$_GET['page'] == $this->view['total_pages']) {
                                $disabled2 = 'disabled';
                            } else {
                                $disabled2 = '';
                            }
                            ?>
                            <ul class="pagination">
                                <li class="paginate_button previous <?php echo $disabled1; ?>" id="example2_previous">
                                    <a class="page-link"
                                       href="?controller=admin-article&action=list&page=<?php echo $previous; ?>">Trước</a>
                                </li>
                                <?php
                                for ($page = 1; $page <= $this->view['total_pages']; $page++) {
                                    if (@$_GET['page'] == $page) {
                                        $active = 'active';
                                    } else {
                                        $active = '';
                                    }
                                    echo '<li class="paginate_button ' . $active . '"><a class="page-link" href="?controller=admin-article&action=list&page=' . $page . '">' . $page . '</a></li>';
                                }
                                ?>
                                <li class="paginate_button <?php echo $disabled2; ?>" id="example2_next">
                                    <a class="page-link"
                                       href="?controller=admin-article&action=list&page=<?php echo $next; ?>">Sau</a>
                                </li>
                            </ul>
                            <?php
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.box-body -->
</div>