<div class="box">
    <div class="box-header">
        <h3 class="box-title">Sửa phòng: <?php echo @$this->view['data']['ten_phong'] ?></h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <?php
        if (!empty($this->view['msg'])) {
            echo '<pre>';
            foreach ($this->view['msg'] as $msg){
                echo $msg.'<br>';
            }

            echo '</pre>';
        }
        if(!empty($this->view['data'])){
        $data = $this->view['data'];
        ?>
        <form action="" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label for="text">Tên phòng</label>
                <input class="form-control" type="text" name="txt_ten_phong" value="<?php echo $this->view['data']['ten_phong']; ?>">
                <label for="text">Mô tả</label>
                <textarea rows="10" class="form-control" id="content" name="txt_mo_ta"><?php echo $this->view['data']['mo_ta']; ?></textarea>
                <label for="text">Thiết bị</label>
                <textarea rows="10" class="form-control" id="content2" name="txt_thiet_bi"><?php echo $this->view['data']['thiet_bi']; ?></textarea>
                <div class="row">
                    <div class="col-sm-6">
                        <label for="text">Số giường</label>
                        <input class="form-control" type="number" name="txt_so_giuong" value="<?php echo $this->view['data']['so_giuong']; ?>">
                        <label for="text">Số người</label>
                        <input class="form-control" type="number" name="txt_so_nguoi" value="<?php echo $this->view['data']['so_nguoi']; ?>">
                        <label for="text">Diện tích</label>
                        <input class="form-control" type="text" name="txt_dien_tich" value="<?php echo $this->view['data']['dien_tich']; ?>">
                    </div>
                    <div class="col-sm-6">
                        <label for="text">Giá</label>
                        <input class="form-control" type="text" name="txt_gia" value="<?php echo $this->view['data']['gia']; ?>">
                        <label for="text">Giá khuyến mại</label>
                        <input class="form-control" type="text" name="txt_gia_km" value="<?php echo $this->view['data']['giam_gia']; ?>">
                        <label for="text">Khách sạn</label>
                        <select class="form-control" name="txt_khach_san" id="">
                            <option value="<?php echo $this->view['data']['id_khach_san']; ?>"><?php echo $this->view['data']['ten_khach_san']; ?></option>
                            <?php foreach ($this->view['list-hotel'] as $value) { ?>
                                <option value="<?php echo $value['id']; ?>">
                                    <?php echo $value['ten_khach_san']; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <label for="text">Hình Ảnh</label>
                <div class="row">
                    <?php
                    $hinh_anh = unserialize($data['hinh_anh']);
                    foreach ($hinh_anh as $value){ ?>
                        <div class="col-sm-3">
                            <img style="width:100%;" src="<?php echo template_url.'images/img-hotel/'.$value; ?>"/>
                        </div>
                    <?php } ?>
                </div>
                <br><input class="form-control" type="file" name="txt_hinh_anh[]" accept=".png,.jpg,.jpeg,.gif" multiple="multiple">
            </div>
            <input type="submit" value="Cập nhật" class="btn btn-info" name="btnSave">
        </form>
<?php } ?>
    </div>
    <!-- /.box-body -->
</div>
<script src="<?php echo template_url; ?>ckeditor/ckeditor/ckeditor.js"></script>
<script>
    //    CKEDITOR.replace( 'noi_dung_ks' );
    //    CKEDITOR.replace( 'thong_tin' );
    CKEDITOR.replace("content",{
        toolbar: [
            { name: 'basicstyles', items : [ 'Bold','Italic','Underline','Strike','-','RemoveFormat' ] },
            { name: 'clipboard', items : [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ] },
            { name: 'insert', items : [ 'Image','Flash','Table','HorizontalRule','Smiley','SpecialChar','PageBreak','Iframe' ] },
            { name: 'paragraph', items : [ 'NumberedList','BulletedList','-','Outdent','Indent','-','Blockquote' ] },
            { name: 'links', items : [ 'Link','Unlink','Anchor' ] },
        ],
        extraPlugins: "tableresize"
    });
    CKEDITOR.replace("content2",{
        toolbar: [
            { name: 'basicstyles', items : [ 'Bold','Italic','Underline','Strike','-','RemoveFormat' ] },
            { name: 'clipboard', items : [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ] },
            { name: 'insert', items : [ 'Image','Flash','Table','HorizontalRule','Smiley','SpecialChar','PageBreak','Iframe' ] },
            { name: 'paragraph', items : [ 'NumberedList','BulletedList','-','Outdent','Indent','-','Blockquote' ] },
            { name: 'links', items : [ 'Link','Unlink','Anchor' ] },
        ],
        extraPlugins: "tableresize"
    });
</script>