<div class="box">
    <div class="box-header">
        <h3 class="box-title">Danh sách phòng</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap"><div class="row"><div class="col-sm-6"></div><div class="col-sm-6"></div></div><div class="row"><div class="col-sm-12"><table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                        <thead>
                        <tr role="row">
                            <th>STT</th>
                            <th>ID</th>
                            <th>Tên phòng</th>
                            <th>Giá</th>
                            <th>Giá khuyến mãi</th>
                            <th>Trạng thái đặt</th>
                            <th>Trạng thái đăng</th>
                            <th>Khách sạn</th>
                            <th colspan="3"></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        $stt = 0;
                        foreach($this->view['list'] as $data){
                            $stt +=1;
                            ?>
                            <tr role="row" class="odd">
                                <td><?php echo $stt; ?></td>
                                <td><?php echo $data['id'] ?></td>
                                <td><?php echo $data['ten_phong'] ?></td>
                                <td><?php echo $data['gia']; ?></td>
                                <td><?php echo $data['giam_gia'] ?></td>
                                <td><?php
                                    if($data['trang_thai']==0){
                                        echo 'Phòng trống';
                                    }
                                    else
                                        echo 'Đã đặt';
                                     ?>
                                </td>
                                <td><?php
                                    if($data['trang_thai_dang']==0){
                                        echo 'Chưa duyệt';
                                    }
                                    else
                                        echo 'Đã duyệt';
                                    ?>
                                </td>
                                <td><?php echo $data['ten_khach_san'] ?></td>
                                <td align="center"><a href="?controller=admin-room&action=edit&id=<?php echo $data['id']; ?>" title="Sửa"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a></td>
                                <td align="center"><a href="?controller=admin-room&action=delete&id=<?php echo $data['id']; ?>" title="Xóa"><i class="fa fa-trash-o" aria-hidden="true"></i></a></td>
                                <td align="center"><a href="#" title="Xem chi tiết"><i class="fa fa-eye" aria-hidden="true"></i></a></td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table></div></div>
            <div class="row">
                <div class="col-sm-5">
                    <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Tổng số: <?php echo count($this->view['list'])?> bản ghi</div>
                </div>
                <div class="col-sm-7">
                    <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                        <?php
                        if ($this->view['total_pages'] > 1) {
                            $previous = isset($_GET['page']) ? $_GET['page'] - 1 : 1;
                            $next     = isset($_GET['page']) ? $_GET['page'] + 1 : 2;
                            if (@$_GET['page'] == 1 || !isset($_GET['page'])) {
                                $disabled1 = 'disabled';
                            } else {
                                $disabled1 = '';
                            }
                            if (@$_GET['page'] == $this->view['total_pages']) {
                                $disabled2 = 'disabled';
                            } else {
                                $disabled2 = '';
                            }
                            ?>
                            <ul class="pagination">
                                <li class="paginate_button previous <?php echo $disabled1; ?>" id="example2_previous">
                                    <a class="page-link"
                                       href="?controller=admin-room&action=list&page=<?php echo $previous; ?>">Trước</a>
                                </li>
                                <?php
                                for ($page = 1; $page <= $this->view['total_pages']; $page++) {
                                    if (@$_GET['page'] == $page) {
                                        $active = 'active';
                                    } else {
                                        $active = '';
                                    }
                                    echo '<li class="paginate_button ' . $active . '"><a class="page-link" href="?controller=admin-room&action=list&page=' . $page . '">' . $page . '</a></li>';
                                }
                                ?>
                                <li class="paginate_button <?php echo $disabled2; ?>" id="example2_next">
                                    <a class="page-link"
                                       href="?controller=admin-room&action=list&page=<?php echo $next; ?>">Sau</a>
                                </li>
                            </ul>
                            <?php
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /.box-body -->
</div>